POST http://localhost:8180/realms/banditgames/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=banditgames-client&client_secret=QLonjXB5IgPtkkNbOuMV9vOyLR3CymL4&username=player1&password=password&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token)
%}


### Search players use case

GET http://localhost:8091/api/players?username=player2
Accept: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("player2_id", response.body.playerId)
%}

### Get games use case

GET http://localhost:8091/api/games
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}



### Create lobby use case

POST http://localhost:8091/api/games/05c99486-9f64-49d4-bbb4-22e40d649ada/lobbies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("lobby_id", response.body.id)
%}

### Get open lobbies

GET http://localhost:8091/api/lobbies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Player1 invites player2

POST http://localhost:8091/api/invites/{{lobby_id}}/invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "userId": "e12bb6fd-8e23-40fd-95cc-f318abf3c38c"
}

> {%
    client.global.set("invite_id", response.body.id)
%}

### Player1 attempts to join own lobby - should fail

PATCH http://localhost:8091/api/lobbies/{{lobby_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Player1 gets game recommendations

GET http://localhost:8091/api/game-recommendations
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###

POST http://localhost:8180/realms/banditgames/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=banditgames-client&client_secret=QLonjXB5IgPtkkNbOuMV9vOyLR3CymL4&username=player2&password=password&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token)
%}


### Player2 uses invite to join

PATCH http://localhost:8091/api/invites/{{invite_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "action": "ACCEPT"
}

### Get open lobbies - should fail (no open lobbies, 204)

GET http://localhost:8091/api/lobbies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}


### Player2 joins lobby (now closed) - should fail


PATCH http://localhost:8091/api/lobbies/{{lobby_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}


