services:
  sonarqube:
    image: sonarqube:9.9.8-community
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - ./sonarqube_db:/var/lib/postgresql
      - ./sonarqube_db_data:/var/lib/postgresql/data
